### ISSUE TITLE
Fail if uneven channel spacing

### ISSUE THREAD

**Issue by nudomarinero** [lofar-astron/prefactor#13]
The prefactor pipeline will fail in the BBS solve and correct step if any of the sub-bands is missing. One single sub-band lost makes the whole 10 sub-band block to fail with the following error: 
```
DEBUG - Assertion: allEQ(upFreq-lowFreq,freqstep0); Channels are not evenly spaced. This is not supported.
FATAL - bbs-reducer terminated due to an exception: [AssertError: Assertion: allEQ(upFreq-lowFreq,freqstep0); Channels are not evenly spaced. This is not supported.]
```
I am working with datasets that have some missing sub-bands due to an early failure of the storage cluster and that cannot be recovered. They are less than 10% of the data but are evenly distributed along the bandwidth. This error would imply to loose more than 60% of the data. 

Is there any way to solve this problem?

**Comment by twshimwell** [comment]
I thought this was fixed some time ago. Are your subbands numbered such that there is a missing number corresponding to the missing subband. I think presently the code which looks for missing subbands uses the name of the data for each subband. However, Andreas has something ready to test which works with the frequency information rather than the names.

**Comment by nudomarinero** [comment]
Yes, they are numbered in order and there is a gap. In any case, I am checking now that it fail in all the 10 sb blocks with the same error even if there is not a gap. I will keep debuging.

**Comment by AHorneffer** [comment]
The current release and master version of prefactor need consecutive subband-numbers to be consecutive in frequency. (It sorts MSs by file-name.) If there are just files missing (because some processing step is missing or whatever), then it should deal with that. If the observation was set up to omit some of the frequencies then it will fail with the error that you reported.

The new version (branch "v2.0-devel") actually looks into the SPECTRAL_WINDOW table and sorts the files by actual frequency.

**Comment by nudomarinero** [comment]
OK, the problem is not caused by the gaps. They are correctly covered by the pipeline. 
My MS have 5 channels per sub-band. They were obtained by dropping the 4 channels of the edges (2+2). The remaining 60 channels were combined in chunks of 12 to get the final 5 channels. This produces an uneven spacing of the channels that may be producing the problem (?). See the picture with the spacing of the channels in the combined 10 sub-band MS:
http://i.imgur.com/eJAZMDb.png

**Comment by nudomarinero** [comment]
This works with LOFAR 2.12. LOFAR 2.15 is required to run the generic pipeline but does not support the uneven spacing and LOFAR 2.12 support the uneven spacing but does not have the generic pipeline. Awful.

**Comment by tammojan** [comment]
Lofar 2.12 does NOT support the uneven spacing. It just not throws an error and does something wrong.

**Comment by AHorneffer** [comment]
Ouch!
With the older LOFAR software you didn't get an error message from BBS when there was an irregular frequency-axis. What did happen was that BBS just computed results as if the frequency axis was regular. I.e. it produced wrong results!

**Comment by AHorneffer** [comment]
Ah, Tammo-Jan beat me.

What you can do is to re-do the pre-processing (if the raw data is still available) or average to one channel per subband. The latter will create quite a bit of frequency smearing, but it would make your data usable again.

**Comment by twshimwell** [comment]
I think this will be too much frequency smearing and this is a field where the wide field imaging is the science rather than an object in the centre. Is guess you don't have the raw data to recombine? I'm not sure how much this issue will effect the long baselines but as a work around is it not possible to use BBS from LOFAR 2.12 within the pipeline from LOFAR 2.15? 

What is the future with NDPPP Tammo? Will that support uneven frequency coverage?

**Comment by nudomarinero** [comment]
OK, thanks for the answers, they are really useful. The original data is not available and cannot be reprocessed.
I suppose that the effect would depend on how much the central frequency of the channel differs from the theoretical evenly spaced frequency. In my case it is really not much (http://i.imgur.com/CUTyiHU.png) but I wonder if it is safe to make the assumption that this small change will not affect the calibration. In the past it worked apparently OK.

**Comment by AHorneffer** [comment]
If you want to use wrong frequency values, then I'd suggest to write a script that fiddles with the frequency values in the SPECTRAL_WINDOW table of the MSs and not try to trick the software to work together with a buggy version of BBS.

**Comment by rvweeren** [comment]
Yes, I think it is better to do this in an external script. I suspect that just "faking" the "freq-axis" is fine, since the difference is very small. The reason is that if you would average a bit more you would not be able to see the difference anyway.

**Comment by nudomarinero** [comment]
The script to modify the frequencies is here: https://github.com/nudomarinero/Astrocompute-ELAIS-N1/blob/master/pipeline/scripts/even_frequencies.py

**Comment by AHorneffer** [comment]
If you want to use the output in Factor, then you have to make sure that your frequency-axis includes the removed channels at the beginning and end of the concatenated MS. (I.e. so that you can concatenate the resulting MSs in frequency and get a regular frequency axis.)

No, I don't want a script to mangle data in the prefactor repository. You could out it into the LOFAR-Contributions repository: https://github.com/lofar-astron/LOFAR-Contributions

**Comment by nudomarinero** [comment]
Thank you for the hint about Factor, I will take that into account in a revised version of the code.

OK.
