### ISSUE TITLE
useage of dysco in prefactor 3.0

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#183]
From very recently observatory is now compressing data with dysco in the LTA and I thought that once data has been dyscod once it shouldnt be dyscod again (does this also apply if you e.g. derive CORRECTED_DATA from a dyscod DATA column -- are you then able to compress CORRECTED_DATA or is this double dysco?)

On data that is already dyscod by the observatory I think that in the present version of prefactor3.0 the DATA column would have dysco run on it multiple times where each time would increase the noise a little bit. 

If, as the observatory already run dysco on the data, should we dysco again at all? (maybe just for archiving very final data products or something)

**Comment by rvweeren** [comment]
As far as I understand it, every time you -write- a column  or MS you have to dysco it, if you do not do that it just writes the uncompressed column/MS.

Not sure if you write many times you slowly increase the noise, I have been wondering about that too.

**Comment by aroffringa** [comment]
If you recompress already compressed data, the noise does indeed increase, so this should be avoided. The reason it does increase is because Dysco explicitly adds a specific kind of noise ("jitter") to the input signal to make the compression unbiased.

As long as you write to a new column, Dysco compression is not enabled even if the data is coming from a compressed column. However, if you write to an already compressed column (e.g. `msin.datacolumn=DATA`, `msout=.`, `msout.datacolumn=DATA`, the column already has an "DyscoStManager", and therefore the output data will be compressed again. Bottomline is therefore that as long as you never rewrite the compressed column and don't compress new columns it should be okay.

Twice compressed data wouldn't of  course add that much noise btw, since most data is compressed with 16 channels/1s, and that is such a high resolution that the compression noise is <<1%. So if used for the input and for the final archived products it should be ok. Nevertheless, the fewer times the data is compressed, the better.

**Comment by adrabent** [comment]
@aroffringa 

>   However, if you write to an already compressed column (e.g. msin.datacolumn=DATA, msout=., msout.datacolumn=DATA, the column already has an "DyscoStManager", and therefore the output data will be compressed again. 

So in such a case I should not call the StorageManager again?

`msout.storagemanager = "Dysco"`

**Comment by tikk3r** [comment]
When I leave out the the `msout.storagemanager = dysco` part, the DPPP output says "compressed: no" though. Even when writing to the same column. Just to have it clear to me, am I then correct in assuming that this just means it's not compressing the data it's writing, and that it will still be compressed because the column already has the DyscoStManager, as you explained?

F

**Comment by aroffringa** [comment]
@adrabent When writing to an already existing column, setting the storage manager does not do anything. It is only for new columns or a completely new MS that you get to chose whether to compress or not.

@tikk3r I think the answer is the same: indeed leaving out msout.storagemanager=dysco part would make DPPP say "compressed: no", which you should interpret as "when DPPP would add a new column, it would not use the compressing storage manager" . Nevertheless, existing compressed column will be compressed.

I realize this is somewhat confusing, but it is part due to how measurement sets work, and that it is not possible to change the storage manager of an existing column (i.e., without doing a "add new column -> delete old column -> rename new column" sequence, which has its problems too (might not free up the space of the old column)).

**Comment by tikk3r** [comment]
> I think the answer is the same: indeed leaving out msout.storagemanager=dysco part would make DPPP say "compressed: no", which you should interpret as "when DPPP would add a new column, it would not use the compressing storage manager" .

Ah that clears things up then.

> However, if you write to an already compressed column (e.g. `msin.datacolumn=DATA`, `msout=.`, `msout.datacolumn=DATA`, the column already has an "DyscoStManager", and therefore the output data will be compressed again.

Does this then also mean writing e.g. a dyscoed `DATA` column to a `DATA_OUT` column and specifying `msout.storagemanager = dysco` will recompress the data? I guess my question is, when reading from a compressed column and writing to a new column, should you specify dysco for that new column or would that recompress it?

The way I understand it now is that if say `DATA` is compressed, and I do something and write to `CORRECTED_DATA`, it would recompress the data, essentially having double compression?

**Comment by aroffringa** [comment]
@tikk3r That is correct, compression would be applied twice in that case. This even happens if you don't change the data.

Of course, it doesn't need to be problematic when intermediate products are compressed twice, as long as it is not done unnecessary. So it will be good to understand what's happening when :). I'm happy to check the workflow at some point to see if unnecessary compressions are done.

**Comment by tikk3r** [comment]
@aroffringa  Ah I see now, thanks for the explanation. I misunderstood how the storagemanager worked and was confused by the DPPP output regarding compression.

**Comment by adrabent** [comment]
@aroffringa 
There are two main things which prefactor 3.0 is doing:

-  Take the `DATA` column, apply some solutions and write a **new** `CORRECTED_DATA` column
-  Take a `DATA` column, apply some solutions and **overwrite** an existing `CORRECTED_DATA` column

When should/need I use the storage manager now to ensure that every column used is actually compressed but not twice?
Especially, we have to treat the case that the input data is already compressed right at the beginning, which will be the case for all future observations.

**Comment by adrabent** [comment]
@aroffringa 
Okay.. that simply means: Once I start from a compressed `DATA` column I should not use the StorageManager anymore if I write a `CORRECTED_DATA` column.

In case I take a compressed `DATA` or `CORRECTED_DATA` column and want to write it into a `DATA` of a **new** measurement set I guess I would also compress it a second time?

**Comment by darafferty** [comment]
Regarding compression of the weights: does the same apply for them too? In other words, does reading a compressed weights column and then writing a new MS with compression on the weights add noise to the weights? And even if it does, is it something to worry about, given that the weights are not terribly well determined to begin with? I am wondering because, as currently implemented, all compression done in Prefactor is done only on the weights, not the data (i.e., databitrate = 0).

**Comment by aroffringa** [comment]
The weights behave differently, and I think you can compress the weights multiple times without adding more noise.

The compression of weights consists of two parts:
i) only 1/4 polarizations is stored
ii) They are quantized (and unlike the DATA col, no noise is added)

Doing i) multiple times of course does not matter. Step ii) is like normal "floating point" round errors. Just reading a value and rewriting it _should_ not add new quantization noise, so I think recompression of weights should be fine. Also note that this only applies when you create a new compressed measurement set from an old ms, or when you rewrite the weight col, which normally doesn't happen in a loop or something. Furthermore, because the weights are already 1/8th of the DATA col (not complex, one pol) I chose to use a very mild quantization using 16 bit (whereas DATA uses 10 bits), so all in all my estimate is that the quantization noise is negligible even after several recompressions.

And I think you're also right that compressing the weights, which hold a rather low amount of information, should have little effect, even if they were e.g. 10% changed -- whereas in reality they won't change by more than a tenth of % or so.

**Comment by darafferty** [comment]
OK -- thanks. In this case I think we should always compress the weights when making new MS files in Prefactor (at the very least -- maybe the DATA too in some cases). So, @adrabent, I would re-enable the compression as you had it previously.

**Comment by adrabent** [comment]
The discussion on how to use dysco in prefactor now has converged.
