### ISSUE TITLE
subtract step

### ISSUE THREAD

**Issue by mhardcastle** [lofar-astron/prefactor#19]
In what I think is the subtract_high step of the Initial Subtract pipeline, the keywords to specify how many ndppps should be run per node don't seem to be being honoured. With

! max_dppp_per_node         =  1
! max_dppp_threads          =  16

I am actually getting 6 or 7 ndppps per node, all trying to run with 16 threads. Not exactly a problem other than that the nominal load is quite high, but it's inefficient.

I'm afraid I have no idea which bit of code is responsible for this! Presumably the generic pipeline itself. But on the off-chance that this is a problem with the parset, I raise it here.

**Comment by AHorneffer** [comment]
I don't see a problem in the pipeline parset (which doesn't mean there isn't one).
Can you put the pipeline logfile somewhere where I can find it?

**Comment by wllwen007** [comment]
I hadn't actually noticed it doing this, but something looks a bit fishy in one of my logs:

Of the 3 NDPPP calls (all with max_dppp_per_node set to 1), the two subtract ones show
Limiting to 16 simultaneous jobs/node
and spawns 3-4 per node (because I had 6 nodes and 24 bands)
and the correct,avg one shows:
Limiting to 1 simultaneous jobs/node
and spawns only 1 per node.
See full log here ftp://star-ftp.herts.ac.uk/pub/Williams/Initial-Subtract_L343224_pipeline.log (can't seem to make this a link)

As far as I can tell the pre-facet-cal calls to dppp obey their restrictions.

**Comment by AHorneffer** [comment]
O.K. It's either the "control.inplace = True" in which case it would be a bug in the genericpipeline.
Or it's because in those steps the other control values were given as "...control.ops..." and the "max_per_node" only had "...control...". (They should be the same, but maybe the pipeline doesn't like mixing them.)

I remove the "opts." from the new version. Can you test if that fixes the issue?

**Comment by AHorneffer** [comment]
I guess this works now.

**Comment by mhardcastle** [comment]
Not tested yet I'm afraid. I'll reopen if there's a problem.
