### ISSUE TITLE
confusing input

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#195]
https://github.com/lofar-astron/prefactor/blob/0318cfe545025ae3cdb07b502b8b6d61fd1c636b/Pre-Facet-Target.parset#L55

Seems like this line is user -required- input so should not occur here. Also provide explanation (this needs to point the the calibrator products).

**Comment by tikk3r** [comment]
I took another look and this is, after all, already defined in `pipeline.cfg`. It is automatically created as `<runtime_direcytory>/Pre-Facet-Calibrator` or `<runtime_direcytory>/Pre-Facet-Target` for example.

**Comment by adrabent** [comment]
@rvweeren
Hmm.. sorry. I dont't get the point. What is the real issue here?
It is explicitly stated to be NOT a required input and should be left to the default as long as you know what you are doing. The parameters which are (very) likely to be adjusted are listed in the first two paragraphs.

Just for understanding:
The job_directory is a variable which is definied in the `pipeline.cfg` and is usually runtime_directory + job_name. The definition here is only used to simplify and parset and keep it clean.

**Comment by rvweeren** [comment]
This was related to my previous point and what First mentioned, it is unclear/confusing to a user where to put the information in the target parset about the path of of the calibrator calibration files and the target files.

**Comment by rvweeren** [comment]
#194 #196 

I think this one can be closed as it related to the other issues.
