### ISSUE TITLE
ndppp_prep_targ error:  SolTab has no element DE601HBA in ant

### ISSUE THREAD

**Issue by apmechev** [lofar-astron/prefactor#198]
Running prefactor target parset on L229587 with the latest version of prefactor gives this error:

```

[Exception: SolTab has no element DE601HBA in ant]
in function hsize_t LOFAR::H5Parm::SolTab::getNamedIndex(std::map<std::basic_string<char>, long long unsigned int>&, const string&, const string&)
(/opt/lofar/lofar/src/CEP/DP3/DPPP/src/SolTab.cc:427)

```

We use [the lofar singularity image here](https://lofar-webdav.grid.sara.nl/singularity/production/lofar.simg).

Full log is [here](https://lofar-webdav.grid.sara.nl/logs/SKSP/pref_targ2/test_target1.out?action=show)

**Comment by adrabent** [comment]
This issue is related to: https://github.com/lofar-astron/prefactor/issues/185

Please check the following and report here:
- the station list of the measurement set
- the station list of the `calibrator` soltab in `cal_solutions.h5` (with `losoto -i`)

I guess you both have less stations in the soltab than in the measurement set you try to apply the solutions for. The plugin `check_station_mismatch`, which is run before, indeed seemed to identify that. That's why, as input, you have `msin.baseline:       [CR]S*&;!UK608HBA*;!DE602HBA*;!FR606HBA*;!DE604HBA*;!DE601HBA*;!DE605HBA*;!SE607HBA*;!DE603HBA*`

So, DPPP seems to complain about a station (missing in the SolTab) that is actually asked for being removed before applying the solutions in order to actually avoid a crash. If this turns out to be true, we should refer it to be a "bug" in DPPP.

**Comment by tikk3r** [comment]
Could it be DPPP looks in the ANTENNA table during applycal? This won't change until you write out a new measurement set with antennas filtered out, I think.

**Comment by tikk3r** [comment]
Cool, I'll open a ticket there for reference then. In the mean time I've fixed it (I think, it hasn't crashed yet) locally here in Leiden by first running a filtering step before running the `ndppp_prep_target`.

For the interested, what I've added is here: https://gist.github.com/tikk3r/9b064e59b144beffb58cf8df84d1b3cf

**Comment by tikk3r** [comment]
Maybe interesting as well, if I re-enable

https://github.com/lofar-astron/prefactor/blob/f45da871ea33fe0f3f7f2d5645c03a1b12453e2c/Pre-Facet-Target.parset#L211-L213

with
```
ndppp_prep_target.argument.filter.type                         =   filter
ndppp_prep_target.argument.filter.baseline                     =   check_station_mismatch.output.filter
ndppp_prep_target.argument.filter.remove                       =   true                     # fully kick out the international stations.
```
it seems to work fine (no immediate crash).
