### ISSUE TITLE
question about rotation

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#207]
In the Pre-Facet-Calibrator parset, the calib_cal step (which is repeated multiple times) is rotation+diagonal.  I understand why this is necessary for the first two steps, but is there another rotation besides Faraday Rotation that this is solving for?  Is it necessary to solve for rotation+diagonal in the subsequent steps (after FR is applied)?

**Comment by adrabent** [comment]
Indeed, this is actually a good question.
Theoretically it should not be necessary to re-solve for rotation. In my tests with HBA data I figured out that the phase solutions turn out to be much better if I re-do the rotation solve even after correction for Farady Rotation. Maybe there is still an effect which is not corrected for. That's why I just decided to leave it as it is.

**Comment by lmorabit** [comment]
Perhaps we should have a larger discussion about this, if prefactor is going to diverge from what was published. Have other people also seen an improvement with rotation on?  I sometimes see the opposite in the long baseline data.

**Comment by adrabent** [comment]
You shouldn't see anything different.
I have to correct me. The issue is whether you use `DDEcal` or not:

HBA calibrator results for TEC if using gaincal (diagonal only):
![tec](https://user-images.githubusercontent.com/19146990/52623159-eeab4d80-2eab-11e9-85b9-61dd2e59f6a1.png)
HBA calibrator results for TEC if using DDEcal (diagonal only):
![tec](https://user-images.githubusercontent.com/19146990/52623194-0da9df80-2eac-11e9-8701-21179c7ff03e.png)
HBA calibrator results for TEC if ussing DDEcal (diagonal+rotation)
![tec](https://user-images.githubusercontent.com/19146990/52623224-21554600-2eac-11e9-91c2-07d8155cfc94.png)

There is a clear difference in the first case. The stations RS210, RS409, RS503, RS508, and RS509 do not have any solutions. And it is much more noisy in general.
You see that the diagonal solve in `DDEcal` performs much better (I don't know why) and that there is no difference in the results for TEC (and for clock as well) if I enable diagonal+rotation or just diagonal. But why did I stick to diagonal+rotation? Simply just because the pure diagonal solve in `DDEcal` adds an additional `dir` table in the solution set, which is not of any use in our case. I already have added a report about that last December here: https://github.com/lofar-astron/DP3/issues/97

If you could report your issues in case of long baselines I would appreciate that.

**Comment by lmorabit** [comment]
I'm still testing the long baselines with the newest version of prefactor and will post results when I have them, but I see in your solutions there are still differences between DDEcal diagonal and DDEcal diagonal+rotation -- looking at RS509 for example you can see that the values aren't exactly the same.

I hate to be pedantic, but if we're trying to follow https://www.aanda.org/component/article?access=doi&doi=10.1051/0004-6361/201833867 then we really should follow it (i.e. don't solve for rotation after it's already been removed).

**Comment by adrabent** [comment]
I agree with you.
I will for sure go back to `diagonal`  in `DDEcal` once the `dir` table issue is solved. Or once the direction-independent solve provides as good results. Otherwise `prefactor` fails for many stations in HBA. So we really don't have any other choice I have to admit.

On the other side, you can always solve for `rotation`, since your `FR` solutions are just a fit and you might have residuals left. Incorporating these residuals might still improve your diagonal solve, although for HBA I think you can neglect this effect.

**Comment by adrabent** [comment]
Now the direction table is added to any `h5parm` output:
https://github.com/lofar-astron/DP3/issues/97

The `H5parm_collector.py' is now able to squeeze the solution tables:
https://github.com/revoltek/losoto/commit/42f4914e0310c775d2e0a0bb3a7399a7e342a40e

**Comment by adrabent** [comment]
Rotation is not used anymore for solving after correcting for FR.
