### ISSUE TITLE
correct for ionospheric Farady Rotation with RMExtract

### ISSUE THREAD

**Issue by rvweeren** [lofar-astron/prefactor#22]
Use RMExtract from Maaijke Mevius to corrected for the  ionospheric Farady Rotation.

(can probably be done at the same time when we correct for the beam in the phase center)

[RMExtract](https://github.com/maaijke/RMextract)

More useful info can be found [here](http://www.lofar.org/operations/doku.php?id=students:polarisation_tutorial&s[]=rmsynthesis)

**Comment by AHorneffer** [comment]
I uploaded a first version that adds correction for the ionospheric Farady Rotation as predicted from RMextract to the pipeline. I didn't test this on actual data yet, so there are probably a couple of bug in there. This implementation runs RMextract for each target MS, which can take a significant amount of time (even though it runs in parallel).

I also split the Pre-Facet-Cal.parset into two parsets, one for the calibrator and one for the target data. These can either run separately or together by using the new version of Pre-Facet-Cal.parset.

**Comment by wllwen007** [comment]
Andreas, I am testing your RMextract branch. I have some bug fixes which I will make a pull request to fix. One change I made is to download the ion files as a separate step (get_ion_files) - without this the trans step gives errors if you leave it to download the files because too many instances try to download the same file (each subband of the same time range/day) and end up corrupting it. I don't think if I've done this in the best way - if I'm not mistaken it only needs to be run for each unique time range (so interleaved obs might need to download more than 1 ion data file), and now it downloads the file on the first MS, then wastes a few cpu cycles checking that the file exists for all other MS's.

**Comment by AHorneffer** [comment]
O.K. So I have merged it now and I think I tidied it up some more.
My main change is that the numpy files are not copied, but directly read from the cal_values_directory. As long as that is not on a file-system that is significantly slower than the local work directory, this should be fine.

**Comment by AHorneffer** [comment]
Ah, as usual I didn't test this, so please do. :-)

**Comment by AHorneffer** [comment]
The current implementation seems to work (well, it doesn't crash), so this can be closed.
Further discussion about a more efficient implementation in: #61
