### ISSUE TITLE
'Soltab' object has no attribute 'freq'

### ISSUE THREAD

**Issue by amisk** [lofar-astron/prefactor#242]
Hi,

While running the target pipeline, I get
`'Soltab' object has no attribute 'freq'`

As I see it, it happens in getStructure_from_phases.py

Cheers

**Comment by adrabent** [comment]
Could you please provide your h5parm and the logfile?

-Alex

**Comment by amisk** [comment]
I think it happened before that in losoto, but also with the last subband group. Maybe it was flagged...
Anyway, here is the log and h5parm file (I assume you mean cal_solutions.h5?)

**Comment by adrabent** [comment]
The crash happend with the `solutions.h5`:
'/data/amisk/scratch/Pre-Facet-Target-L582117/results/cal_values/solutions.h5'

**Comment by amisk** [comment]
`print h5parm(fname).getSolset('sol000').getSoltab('phase000').getAxesNames()`
always results in ['time', 'freq', 'ant', 'pol'] for every h5 file.

**Comment by adrabent** [comment]
Removing the freq axis after merging h5parms has already been reported as a bug and should have been fixed in losoto since this commit:
https://github.com/revoltek/losoto/commit/d35d01772cf5c3fde1222cf0aad0a84e12c21752#diff-f76fc25f6577ee4e3db965b9d0764dd9

Could you check whether you run the most recent losoto version?

**Comment by amisk** [comment]
It was about 3 months old. I installed the master branch again. Let's see.

**Comment by amisk** [comment]
It did it. Thanks.
