### ISSUE TITLE
solutions.h5 target solset contains different number of antennas for RMextract and TGSSphase

### ISSUE THREAD

**Issue by lmorabit** [lofar-astron/prefactor#261]
I have run Pre-Facet-Calibrator and Pre-Facet-Target, and am now trying to apply the solutions from both (which are all contained in the solutions.h5 from Pre-Facet-Target pipeline) to my target data.  

The error is contained in the attached log but basically boils down to 
`[Exception: SolTab has no element RS508HBA in ant]`

When I inspect solutions.h5, I see that in the target solset, RMextract has 75 antennas but TGSSphase only has 74.  Inspecting ph_polXX.png I see that indeed, RS508 is not there.  If I look at the Pre-Facet-Target pipeline.log file, I see that somewhere this station is being picked up for flagging and fed to dpppconcat.

[pipeline.log](https://github.com/lofar-astron/prefactor/files/3911562/pipeline.log)

**Comment by adrabent** [comment]
If `RS508HBA` was identified as bad antenna, this will be the intended behaviour.
Please check your `solutions.h5` file or the summary file if this was the case.

FYI: It is only mentioned in the `solutions.h5` if you use the new version of `losoto`.
Often this is the case, because target data is really identified to be corrupted (before the actual self-calibration) or the corresponding solution tables from the calibrator are flagged by 100%. If this is the case you may check if something went wrong during the calibrator calibration.

If you want to apply these solutions you should filter out the bad station anyways and then you should be able to apply them.

**Comment by lmorabit** [comment]
Can you please specify exactly how I am supposed to filter this bad station, because I tried flagging and not selecting it with msin.baseline already and still had this error.

**Comment by adrabent** [comment]
Ah right.. this is still the DPPP bug and has been discussed here:
https://github.com/lofar-astron/prefactor/issues/198
https://github.com/lofar-astron/DP3/issues/95

In short, the current workaround is to use a `filter` step before you apply as done by prefactor in the target pipeline automatically:

https://github.com/lofar-astron/prefactor/blob/master/Pre-Facet-Target.parset#L315-L317

**Comment by lmorabit** [comment]
Thank you, that worked.
