### ISSUE TITLE
Python3 "Validation of data mafiles failed!" errors

### ISSUE THREAD

**Issue by aroffringa** [lofar-astron/prefactor#272]
I am running the prefactor calibrator pipeline on a single machine, and every now and then I get this error:

```2020-06-13 16:19:12 ERROR   genericpipeline.executable_args: Validation of data mapfiles failed!```

Rather than an actual error, there seems to be something incorrect in the checking mechanism, because no tasks have failed, and by restarting the pipeline it passes the same point without a problem. To complete the calibrator pipeline, I needed to restart it on the order of five times.

I'm using Python 3 with the fixes from my PR. Could it be that the generic pipeline has Python 3 issues?

**Comment by tikk3r** [comment]
> Could it be that the generic pipeline has Python 3 issues?

In my experience yes. I have tried, but so far have not gotten generic pipeline / prefactor to run properly under Python 3. I did some ad hoc fixes with `2to3` to resolve the immediate Python related issues, but I also run into trouble with mapfiles such as, for example, step B failing to use the output/mapfile(s) of step A, yet running fine when restarted manually.

**Comment by aroffringa** [comment]
Ugh! Is the CWL port going to solve that?

**Comment by adrabent** [comment]
@aroffringa 
The `CWL` version will not use the genericpipeline framework and thus no mapfiles etc. anymore. Current test runs with the current prefactor calibrator pipeline were successful.
David tried to translate the genericpipeline framework to python3, but faced many issues in the mapfile modules, which in the end turned out, that we have to re-write those modules to get them work with python3. We thus stopped this part and focus on the CWL implementation for full python3 support.

**Comment by adrabent** [comment]
If issues still occur, try out the new version, based on CWL: https://git.astron.nl/eosc/prefactor3-cwl
