### ISSUE TITLE
freq_width too large when every other subband is missing

### ISSUE THREAD

**Issue by cgroeneveld** [lofar-astron/prefactor#279]
https://github.com/lofar-astron/prefactor/blob/e3835d53253b39b830a6edf1d4aab48218d6f287/scripts/sort_times_into_freqGroups.py#L204

When every other subband is systematically missing, the minimum spacing will be twice as big as expected (400 kHz instead of the normal 200 kHz per subband). Is there any specific reason why freq_width is not fixed?

**Comment by rvweeren** [comment]
To clarify further. We have a dataset where every other subband is missing. Then de code computes an incorrect  freq_width (it computes a freq_width  2 x 195 kHz instead of 195 kHz). So in this dataset there are no subbands that "touch" each other. Would it not be better to hard code the frequency spacing since this is set by the hardware? (195.3125 kHz/SB)

**Comment by adrabent** [comment]
@rvweeren  .. this is a good point. And the hardware resolution is the same for HBA and LBA. I think it may be good to just fix it to that value.

**Comment by rvweeren** [comment]
@adrabent it is worse than 'hurt', it will crash prefactor to crash via https://github.com/lofar-astron/prefactor/blob/caabd0f8f20693cf61bae55b348c978cd1f0d8d3/scripts/sort_times_into_freqGroups.py#L208

**Comment by adrabent** [comment]
Right. I just checked the code and I think it was intentionally done. The `freq_width`  is compared with the `file_bandwidth`, which is extracted from the MS tables and matches the hardware's frequency spacing. 

If we will just set freq_width to the frequency spacing of the MS, we could also just skip this step, because checking would not make any sense any more. I could only imagine that this check would make sense if bands are really missing. Maybe there was an idea of a certain scenario behind that that we are not aware of
