### ISSUE TITLE
Is Prefactor ready for AOFlagger 3, DP3 5 and EveryBeam?

### ISSUE THREAD

**Issue by AlexKurek** [lofar-astron/prefactor#282]
Just a quick question - can we use the new versions, or should we for now still use AOFlagger 2.15, DP3 4.2 and LOFARBeam?

**Comment by adrabent** [comment]
Dear Alex,

happy new year. In principle prefactor3 may also work with the newest version of DP3 and AOFlagger. I have not yet tested against it. I heard issues running the newestlosoto with the pipeline, probably because of some nasty python2/python3 conflicts.
The new prefactor3-CWL version is tested against the most recent DP3. It is planned to be published in the near future.

Alex

**Comment by adrabent** [comment]
The new prefactor is using state-of-the-art software:
https://git.astron.nl/eosc/prefactor3-cwl
