### ISSUE TITLE
gsmsol plot in v2.0-devel

### ISSUE THREAD

**Issue by wllwen007** [lofar-astron/prefactor#29]
The phase plotting in v2.0-devel doesn't seem to include all my bands - I had 24 bands (running on 4 machines) yet the plot only seems to show 6 separate frequencies:

![gsm_phases](https://cloud.githubusercontent.com/assets/2170761/14423140/19d9b6d8-ffd2-11e5-970f-58c9153ed11c.png)

The h5imp_gsmsol_losoto.h5 file has a frequency axis of length 6.

I think the mapfile going in to the losoto importer (excuse the .txt extensions to make it upload here) - is making it run 6 MS's on each of my 4 nodes instead of importing them all in a single losotoimporter call:
[h5_imp_gsmsol_map.mapfile.txt](https://github.com/lofar-astron/prefactor/files/212670/h5_imp_gsmsol_map.mapfile.txt)

I noticed now that the log actually has some errors related to this (only one of the 4 was successful) which it continued past (because there is no error_tolerance on these losoto steps):
[pipeline.log.txt](https://github.com/lofar-astron/prefactor/files/212671/pipeline.log.txt)

**Comment by twshimwell** [comment]
is it possible to also change the aspect ratio of these plots like was done in [https://github.com/lofar-astron/factor/issues/26](url)

**Comment by wllwen007** [comment]
Tim, I think that would need to be changed in losoto, although it is easy enough to do.

**Comment by AHorneffer** [comment]
Oh, you actually use the "hosts" value in the mapfiles. I'm actually surprised that you got this far without loosing 3/4 of your data in between. Why did "MapfilenamesFromMapfiles" (step "do_sortmap_maps") not complain that there was more than one entry in the mapfiles it got?

(And the "mapfile_all_to_one" of the "createMapfile" does not behave as I expected it, which is the direct cause of this problem.)

**Comment by rvweeren** [comment]
Can we also make these plots for the primary calibrator ? (would provide more opportunities to spot bad data and gives a good measure of the ionosphere since the S/N should be very hight in this plot)

**Comment by fe56** [comment]
Oh, lets see if i get this right.
Your losoto thingy is taking ONE list of ALL MS there are. But the MultiDataMap class is operating on a per node basis. From the old CEP we-dont-have-shared-storage times.

This would need an extra function to create this mapfile or introducing an additional option, say: all_to_one_single_node
And then changing the constructor of the MultiDataMap class with a boolean for multiple nodes or single node.

**Comment by AHorneffer** [comment]
Reinout: I'm not adding generating these plots for the calibrator ... again.

fe56: (You seem to be Stefan Froehlich, correct?) The problem is not only getting all files into one group (as opposed to getting all files on each node into one group per node), but also to distribute the workload after the files have been re-arranged. 

Tim et al.: If you want to discuss the shape of the plots, then please open another issue.

**Comment by rvweeren** [comment]
Ah, it is already there..sorry.

**Comment by wllwen007** [comment]
Dealing with mapfiles is one of the more opaque parts of the pipeline to me. I'm a bit confused here, because it has apparently worked without problems for other parts of the pipeline. I haven't lost any of my data (only in the losoto step) and I haven't tweaked anything to do with the mapfiles.

I think this has worked because the other step that uses mapfile_all_to_one (combine_target_map ) takes as input the ndppp_prep_target.output.mapfile which contains only localhost as host for all MS's.

**Comment by AHorneffer** [comment]
Having on "localhost" in the host field of the mapfiles is what I expect.

How did you get the actual host-names into the mapfiles? (I don't see where that happened. The sort_times_into_freqGroups.py has a feature to do that, but it isn't used.)
Do you actually need to have the host-names in the mapfiles to have the pipeline distribute the load on multiple nodes?

**Comment by fe56** [comment]
Yes, its Stefan here.

Usually putting the hostnames in the mapfiles would be the way to control where the jobs are running.
Since we dont know our nodes beforehand on Jureca we hacked the pipeline in a different place and replace the hostnames of the jobs. I thought Wendy uses the same strategy so i am not sure why there are hostnames in the mapfile.

Anyway... Andreas, what do you mean by
' but also to distribute the workload after the files have been re-arranged.'
Are you really creating new filenames in the h5imp-cal step? If not it should be possibel to use the ndppp_prep_cal.mapfile for fitclock and following steps right?

I have a modified createMapfile plugin that takes method=mapfile_all_to_one_single_node as argument and only uses the first node for a full list of files (at least in my test). That option should be used in Wendys case as it is right now.


[PipelineStep_createMapfile.py.txt](https://github.com/lofar-astron/prefactor/files/214662/PipelineStep_createMapfile.py.txt)

**Comment by AHorneffer** [comment]
Hi Wendy. It is still unclear to me:
- How the host names were introduced into the mapfiles?
- If your cluster will distribute the workload over all available nodes if all host-entries in the mapfile are "localhost" and/or the name of one of the nodes?

Stefan: I would prefer is the logic were the other way around: if "mapfile_all_to_one" would put all entries into one group independent of host-names, and if something like "mapfile_all_to_one_per_node" would put the entries into one group for each node. But I agree that this might break backward compatibility. Are there cases where this would be a problem?

**Comment by wllwen007** [comment]
Stefan's new PipelineStep_createMapfile.py worked to create one list so only one losotoImporter was run, which is what it should do. 

>How the host names were introduced into the mapfiles?

I think this is picked up somewhere in the flag checking steps (but it could also be the sortmap steps) 
check_unflagged.mapfile : contains only localhost
check_unflagged.flagged.mapfile, check_unflagged_map.mapfile : contains node names
I put the mapfiles here if you want to take a look: ftp://ftp.strw.leidenuniv.nl/pub/wwilliams/mapfiles.tar.bz2


>If your cluster will distribute the workload over all available nodes if all host-entries in the mapfile are "localhost" and/or the name of one of the nodes?

If everything is localhost, the pipeline knows to which nodes it can send jobs (that was the change we made for our cluster - that it looks at the PBS_NODEFILE to learn the available hosts) and obeys all the max_per_node rules. I'm not too sure what it does in the other case because I haven't really had a test case like that.

**Comment by AHorneffer** [comment]
Thanks. I think I understand now what happened. 
I'll need to discuss with Stefan how to best solve this.

**Comment by AHorneffer** [comment]
There is [issue 9643](https://support.astron.nl/lofar_issuetracker/issues/9643) on the LOFAR issue-tracker for this issue. So it can be closed here.
