### ISSUE TITLE
Frequency spacing in amplitude plots

### ISSUE THREAD

**Issue by AHorneffer** [lofar-astron/prefactor#35]
For the gain-amplitude transfer I interpolated the amplitudes from the calibrator onto a regular grid.
Now Wendy submitted a pull request (#34) that uses the original frequencies, which may have holes due to flagged subbands.

I believe the difference is in the subband-numbering in the plots and in the way that the smoothing is done:
Wendy's way will treat values that may be quite a bit apart in frequency (but with all intermediate frequencies flagged) as neighbouring, while my way will smooth the interpolated data.

Any opinions on what you think is the better way?

**Comment by Joshuaalbert** [comment]
In terms of smoothing. Your way of interpolating is likely better depending on how you choose to interpolate. If there is good reason for the data to be smooth and there are no higher order structure in the intermediate subbands then a smooth linear interpolation is ideal and wont change the result much for smoothing. The larger the gap the less likely it is that this condition holds and Wendy's method might be better at the cost of bad numbering.
On 14 Apr 2016 19:26, AHorneffer <notifications@github.com> wrote:For the gain-amplitude transfer I interpolated the amplitudes from the calibrator onto a regular grid.
Now Wendy submitted a pull request (#34) that uses the original frequencies, which may have holes due to flagged subbands.

I believe the difference is in the subband-numbering in the plots and in the way that the smoothing is done:
Wendy's way will treat values that may be quite a bit apart in frequency (but with all intermediate frequencies flagged) as neighbouring, while my way will smooth the interpolated data.

Any opinions on what you think is the better way?

**Comment by wllwen007** [comment]
Andreas, thanks for bringing this up as an issue. I probably should have done so first, but thought the change was trivial. Clearly I didn't fully think through all the implications of the interpolation o_O ... I do think the better way is to interpolate onto a uniform freq. grid, i.e. not what I have now done.

The specific case I am testing is for the new 'standard' (cycle5+) survey observations where some frequencies are not observed so there are gaps, and about 10SBs at the top of the band are spaced 2MHz apart (!) I'm not planning on using the top widely spaced SBs for the target (so essentially their amplitudes don't matter), but kept them in for the calibrator thinking the wider freq. coverage would be better for clock-tec fitting. I also have the case that one of these top SBs is bad so the interpolation fails badly.

For example the flagged plots (first the original code and then my change). I know this plot is against SB number to id bad subbands, but in my case this SB number is now wrong:
![cs001hba1_flaggedyy](https://cloud.githubusercontent.com/assets/2170761/14557354/e63a19c8-02f4-11e6-812c-095ef14c11a9.png)
![cs001hba1_flaggedyy](https://cloud.githubusercontent.com/assets/2170761/14558520/dd2da8d0-02fa-11e6-974f-e74d99834c66.png)

and the profile plots (first the original code and then my change)
![cs001hba1_profileyy](https://cloud.githubusercontent.com/assets/2170761/14558536/ee5eb8d8-02fa-11e6-8710-43d99c4c1b96.png)
![cs001hba1_profileyy](https://cloud.githubusercontent.com/assets/2170761/14558542/f3bf0fe4-02fa-11e6-8d9e-9198cfc2ef66.png)

**Comment by AHorneffer** [comment]
Ah, I see your point. (And I don't have a "one size fits all" answer.)
One additional reason I did the interpolation that way was because back then the pipeline didn't work with data that was observed with gaps in the frequency coverage, so my way gave subband-numbers that were the same as the numbers in the file-names of the MSs.

Well, first about the plots. What combination of plotted data and x-axis values do you want?
1. data after flagging of bad (no solutions in BBS, missing data, marked as bad by user etc.) time- frequency- points
2. data as (1) but that was also smoothed with a median filter 
3. data as (2) but also smoothed with a Savitzky-Golay filter
For the x-axis:
A) frequency in MHz
B) subband number as it is set at the station (i.e. 0 == 100MHz, going up to 511 == 200 MHz, independent of which freqeuncies where actually observed)
C) "SB number", starting with 0 at the lowest frequency and then incrementing by one every 195. kHz (which is "my" old way)
D) "SB number" starting with 0 at the lowest frequency and then incrementing by one for every subband where there is data (what Wendy proposed)
