### ISSUE TITLE
plot_cal_phases losoto step hangs if just 1 concat msfile

### ISSUE THREAD

**Issue by twshimwell** [lofar-astron/prefactor#89]
Perhaps this should be on the losoto wiki instead...

Example when h5imp_gsmsol_losoto.h5 is created from just 1 concat msfile

[shimwell@para33 Pre-Facet-Target-P198+42]$ /net/para10/data1/shimwell/pipeline/Pre-Facet-Cal/losoto/build/scripts-2.7/losoto h5imp_gsmsol_losoto.h5 h5imp_gsmsol_losoto.h5.parset 
WARNING: Appending to h5imp_gsmsol_losoto.h5.
INFO: --> Starting 'plot' step (operation: PLOT).
INFO: Plotting soltab: phase000
ERROR: 3D plot must have more then one value per axes.
ERROR: Step 'plot' incomplete. Try to continue anyway.
INFO: Time for this step: 0 s (cpu: 0 s).
INFO: Time for all steps: 0 s.
INFO: Done.

This then just hangs rather than exiting.

**Comment by AHorneffer** [comment]
> INFO: Done.

That is losoto's way to tell you that it has finished. (I.e. it is the last line in the python script.)
Does it actually work on the same machine if you have more than one concat file?

**Comment by twshimwell** [comment]
Yes it works on the same machine doing the same command if the h5 contains e.g. 40subbands. 

The hanging occurs whether or not I use the command inside or outside of the pipeline so I think this is an issue with losoto itself rather than the pipeline.

**Comment by twshimwell** [comment]
I guess it doesnt exit because something is locked but I'm not sure what.

**Comment by wllwen007** [comment]
I think there is a quick patch for losoto to stop the hanging (in losoto/losoto/operations/plot.py the multiprocessing stuff isn't closed when the plotting fails)
279                    logging.error('3D plot must have more then one value per axes.')
                          mpm.wait()
280                    return 1

But the real problem is you are trying to make a 3D phase-freq-time plot when there is only 1 solution in freq (only 1 band) and losoto needs a different parset for that. I suppose that's ok as prefactor does make those plots (phase-time per band)...

**Comment by twshimwell** [comment]
Yeh, this plot is not good when just 10subbands (we are just taking it out when running with 10 subbands). I just wanted to get rid of the hanging behaviour though and the patch you suggested does this nicely.

**Comment by twshimwell** [comment]
fixed in latest losoto.
